site_name: PSCodeHealth
repo_url: https://github.com/MathieuBuisson/PSCodeHealth
site_author: Mathieu Buisson
edit_uri: edit/master/docs/
theme: readthedocs
copyright: "PSCodeHealth is licensed under the <a href='https://github.com/MathieuBuisson/PSCodeHealth/raw/master/LICENSE.md'>MIT license"
pages:
  - Home: index.md
  - Installation: Installation.md
  - Release Notes: Release.md
  - Getting Started: GettingStarted.md
  - Metrics collected by PSCodeHealth: Metrics.md
  - How do I ...:
    - Create and interpret a PSCodeHealth HTML report: HowDoI/HtmlReport.md
    - Check if my code meets metrics goals: HowDoI/CheckCodeCompliance.md
    - Customize compliance rules according to my metrics goals: HowDoI/CustomizeComplianceRules.md
  - Public Functions:
    - Get-PSCodeHealthComplianceRule: PublicFunctions/Get-PSCodeHealthComplianceRule.md
    - Invoke-PSCodeHealth: PublicFunctions/Invoke-PSCodeHealth.md
    - Test-PSCodeHealthCompliance: PublicFunctions/Test-PSCodeHealthCompliance.md

  - Internal Functions:
    - Get-ExternalHelpCommand: InternalFunctions/Get-ExternalHelpCommand.md
    - Get-PowerShellFile: InternalFunctions/Get-PowerShellFile.md
    - Merge-PSCodeHealthSetting: InternalFunctions/Merge-PSCodeHealthSetting.md
    - New-FailedTestsInfo: InternalFunctions/New-FailedTestsInfo.md
    - New-FunctionHealthRecord: InternalFunctions/New-FunctionHealthRecord.md
    - New-PSCodeHealthComplianceResult: InternalFunctions/New-PSCodeHealthComplianceResult.md
    - New-PSCodeHealthComplianceRule: InternalFunctions/New-PSCodeHealthComplianceRule.md
    - New-PSCodeHealthReport: InternalFunctions/New-PSCodeHealthReport.md
    - New-PSCodeHealthTableData: InternalFunctions/New-PSCodeHealthTableData.md
    - Set-PSCodeHealthHtmlColor: InternalFunctions/Set-PSCodeHealthHtmlColor.md
    - Set-PSCodeHealthPlaceholdersValue: InternalFunctions/Set-PSCodeHealthPlaceholdersValue.md
    - Get-FunctionDefinition: InternalFunctions/Get-FunctionDefinition.md
    - Get-FunctionLinesOfCode: InternalFunctions/Get-FunctionLinesOfCode.md
    - Get-FunctionScriptAnalyzerResult: InternalFunctions/Get-FunctionScriptAnalyzerResult.md
    - Get-FunctionTestCoverage: InternalFunctions/Get-FunctionTestCoverage.md
    - Measure-FunctionComplexity: InternalFunctions/Measure-FunctionComplexity.md
    - Measure-FunctionForCodePath: InternalFunctions/Measure-FunctionForCodePath.md
    - Measure-FunctionIfCodePath: InternalFunctions/Measure-FunctionIfCodePath.md
    - Measure-FunctionLogicalOpCodePath: InternalFunctions/Measure-FunctionLogicalOpCodePath.md
    - Measure-FunctionMaxNestingDepth: InternalFunctions/Measure-FunctionMaxNestingDepth.md
    - Measure-FunctionSwitchCodePath: InternalFunctions/Measure-FunctionSwitchCodePath.md
    - Measure-FunctionTrapCatchCodePath: InternalFunctions/Measure-FunctionTrapCatchCodePath.md
    - Measure-FunctionWhileCodePath: InternalFunctions/Measure-FunctionWhileCodePath.md
    - Test-FunctionHelpCoverage: InternalFunctions/Test-FunctionHelpCoverage.md

