#
# Module manifest for module 'Coveralls'
#
# Generated by: jan
#
# Generated on: 3/15/2017
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Coveralls.psm1'

# Version number of this module.
ModuleVersion = '1.0.25'

# ID used to uniquely identify this module
GUID = 'e2956cd7-107a-449c-ba4f-21d5e05d7dda'

# Author of this module
Author = 'JanJoris'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) 2017 JanJoris. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Create and upload code coverage data to Coveralls.io using Pester'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.0'

# List of all files packaged with this module
FileList = @('Coveralls.ps1')

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# Functions to export from this module
FunctionsToExport = @('Publish-Coverage', 'Format-Coverage', 'Get-CoveragePercentage')

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('coveralls.io', 'coveralls', 'pester', 'git', 'codecoverage', 'code', 'coverage')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/JanJoris/coveralls/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/JanJoris/coveralls'

    } # End of PSData hashtable

} # End of PrivateData hashtable

}

